### ISSUE TITLE
User Story : Add comment section 

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/USER-STORIES#4]
As a **runner** I can **add individual and specific comments** so that **I can better convey my thoughts**

## Acceptance Criteria
- Add a comment section for runners
- Allow other runners to see this
- Allow them to reply 

## Tasks
- [ ] Create input field allowing users to input a comment and send to database
- [ ] Style the field to fit within site theme
- [ ] Add reply feature with separate input field

**Comment by SimonMoynihan33** [comment]
## Story points
Baseline story point: Gallery page (1point)
Estimated story point for user story: 
4
