### ISSUE TITLE
User Story: Admin comment section

### ISSUE THREAD

**Issue by SimonMoynihan33** [SimonMoynihan33/USER-STORIES#5]
As an **admin** I will be able to **review and delete comments** so that **the comment section remains a safe and respectable place**

## Acceptance Criteria
- Review comments
- Delete comments if necessary
- Warn or ban users who do not act appropriately
- Filters for certain words to not be allowed to be posted

## Tasks
- [ ] Allow admins to access the database 
- [ ] Delete comment from database and it not show on the site
- [ ] Filter certain words so the input field will not allow bad language or name calling
- [ ] Implement a feature to warn a user through email for inappropriate conduct
- [ ] Admin can ban users when necessary

**Comment by SimonMoynihan33** [comment]
## Story points
Baseline story point: 
Gallery page (1point)
Estimated story point for user story: 
13 points
